package lk.ijse.serenitymentalhealthsystem.controller;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.geometry.Pos;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.util.Duration;
import javafx.scene.control.CheckBox;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import lk.ijse.serenitymentalhealthsystem.App;
import lk.ijse.serenitymentalhealthsystem.bo.BOFactory;
import lk.ijse.serenitymentalhealthsystem.bo.BOTypes;
import lk.ijse.serenitymentalhealthsystem.bo.custom.UserBO;
import lk.ijse.serenitymentalhealthsystem.dto.UserDTO;
import lk.ijse.serenitymentalhealthsystem.entity.Role;


public class LoginController implements Initializable {

    private final UserBO userBO = BOFactory.getInstance().getBO(BOTypes.USER);

    @FXML
    private TextField usernameField;

    @FXML
    private PasswordField passwordField;

    @FXML
    private TextField visiblePasswordField;

    @FXML
    private CheckBox showPasswordCheckbox;

    @Override
    public void initialize(URL url, ResourceBundle rb) {
        // Sync text
        visiblePasswordField.textProperty().bindBidirectional(passwordField.textProperty());

        // Fix layout (VERY IMPORTANT)
        visiblePasswordField.managedProperty().bind(visiblePasswordField.visibleProperty());
        passwordField.managedProperty().bind(passwordField.visibleProperty());

        Platform.runLater(() -> usernameField.requestFocus());

    }

    @FXML
    private void login() throws Exception {
        String username = usernameField.getText();
        String password = passwordField.getText();

        UserDTO user = userBO.login(username, password);

        if (user == null) {
            System.out.println("Invalid login");
            return;
        }

        switch (user.getRole()) {
            case ADMIN:
                loadDashboard("AdminDashboard.fxml");
                break;

            case RECEPTIONIST:
                loadDashboard("ReceptionistDashboard.fxml");
                break;
        }
    }

    private void loadDashboard(String fxml) throws Exception {
        Parent root = FXMLLoader.load(
                getClass().getResource("/view/" + fxml)
        );

        Stage stage = (Stage) usernameField.getScene().getWindow();
        stage.setScene(new Scene(root));
    }

    @FXML
    private void register() throws IOException {
        String username = usernameField.getText();
        String password = passwordField.getText();
        Role role = Role.RECEPTIONIST; // Default role for new users

        UserDTO userDTO = new UserDTO(
                null, // ID will be generated by the database
                username,
                password,
                role
        );

        try {
            boolean result = userBO.saveUser(userDTO);
            if (result){
                System.out.println("User registered successfully!");
                Alert alert = new Alert(Alert.AlertType.INFORMATION);
                alert.setTitle("Registration");
                alert.setHeaderText(null);
                alert.setContentText("User registered successfully!");
                alert.show();
            } else{
                Alert alert = new Alert(Alert.AlertType.ERROR);
                alert.setTitle("Registration");
                alert.setHeaderText(null);
                alert.setContentText("User registration unsuccessfully!");
                alert.show();
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @FXML
    private void togglePasswordVisibility() {
        if (showPasswordCheckbox.isSelected()) {
            visiblePasswordField.setVisible(true);
            passwordField.setVisible(false);
        } else {
            visiblePasswordField.setVisible(false);
            passwordField.setVisible(true);
        }
    }




}
